/******************************************************************************
 * Top contributors (to current version):
 *   Mudathir Mohamed
 *
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Extension to the theory of arithmetic handling the lia* (LIA star) operator.
 */

#ifdef CVC5_USE_NORMALIZ

#ifndef CVC5__THEORY__ARITH__LIASTAR_EXTENSION_H
#define CVC5__THEORY__ARITH__LIASTAR_EXTENSION_H

#include <map>
#include <memory>
#include <vector>

#include "expr/node.h"
#include "libnormaliz/libnormaliz.h"
#include "smt/env_obj.h"
#include "smt/solver_engine.h"
#include "theory/arith/liastar/liastar_proof_generator.h"
#include "theory/ext_theory.h"
#include "theory/theory.h"

namespace cvc5::internal {
namespace theory {
namespace arith {

class InferenceManager;
class TheoryArith;

namespace liastar {

/** Arbitrary-precision integers (the integer type handed to Normaliz). */
typedef mpz_class Integer;
/** A row of arithmetic terms, e.g. the monomials of one cone contribution. */
typedef std::vector<Node> Vector;

/**
 * Extension to TheoryArith deciding the lia* operator STAR_CONTAINS.
 *
 * A literal
 *     (int.star-contains (lambda ((x_1 Int) ... (x_n Int)) p) v_1 ... v_n)
 * asserts that the vector v = (v_1, ..., v_n) belongs to the additive closure
 * (the *star*) of the set S = { x in Z^n : p(x), x >= 0 }, i.e. that v is a
 * finite sum of vectors each satisfying p. The extension decides such literals
 * by reducing them to plain linear integer arithmetic, following
 *
 * - Levatich, M., Bjorner, N., Piskac, R., Shoham, S. (2020).
 *   Solving LIA* Using Approximations.
 *   VMCAI 2020.
 *   https://doi.org/10.1007/978-3-030-39322-9_17
 *
 * The reduction views each convex cell (DNF disjunct) of p as a polyhedral
 * cone, computes the cone's Hilbert basis and module generators with Normaliz,
 * and encodes the star of the union of cells as a system of linear constraints
 * over fresh non-negative multipliers (the "star constraints"). The reduction
 * lemma `literal = star` is sent through TheoryArith's inference manager. See
 * the file comment of liastar_extension.cpp for the full picture.
 *
 * The main entry point is checkFullEffort(...), called by TheoryArith at
 * full/last-call effort with the current candidate arithmetic model. Two
 * strategies are available (option arith-lia-star-lazy):
 * - eager (`eagerCheckStar`): normalize p to DNF and reduce in one shot;
 * - lazy (`lazyCheckStar`): discover one convex cell per refinement round from
 *   models of a persistent incremental subsolver, asserting guarded
 *   under-approximations until every cell is covered.
 */
class LiaStarExtension : EnvObj
{
 public:
  LiaStarExtension(Env& env, TheoryArith& containing);
  ~LiaStarExtension();

  /**
   * Does non-context dependent setup for a node connected to a theory:
   * registers STAR_CONTAINS terms with the extended theory and records that
   * this extension has work to do.
   */
  void preRegisterTerm(TNode n);

  /**
   * Performs the main checks for liastar arithmetic, based on the current
   * (linear) arithmetic model from `arithModel`. This method may already send
   * lemmas, but most lemmas are buffered and sent at LAST_CALL effort by
   * TheoryArith. The motivation for this strategy is to allow other
   * non-terminating theories (e.g. quantifiers, strings) to run full effort
   * checks, before sending the lemmas generated by liastar.
   *
   * For each STAR_CONTAINS assertion this emits a non-negativity lemma and a
   * split on the substituted predicate p[v], and then -- unless the current
   * model already satisfies the literal -- reduces the literal via the eager
   * or lazy strategy.
   *
   * @param arithModel a map of the form { v1 -> c1, ..., vn -> cn } which
   *   represents the linear arithmetic theory solver's contribution to the
   *   current candidate model, where v1, ..., vn are arithmetic variables and
   *   c1, ..., cn are constants
   * @param termSet the set of terms relevant in the current check
   */
  void checkFullEffort(std::map<Node, Node>& arithModel,
                       const std::set<Node>& termSet);

  /** Does this class need a call to check(...) at last call effort? */
  bool hasLiaStarTerms() const { return d_hasLiaStarTerms; }

 private:
  /**
   * Collect from TheoryArith's fact queue the STAR_CONTAINS atoms asserted in
   * the current context. Both polarities are reduced to the positive atom:
   * the reduction lemma `atom = star` handles either polarity (the
   * surrounding SAT solver applies the negation).
   */
  void getAssertions(std::vector<Node>& assertions);

  /**
   * Normalize the body p of the lambda `n` into DNF and render each disjunct
   * as a Normaliz constraint matrix (see `LiaStarUtils::getMatrices`).
   *
   * @param n a lambda (lambda ((x_1 Int) ... (x_n Int)) p) with p in QF_LIA
   * @return one (constraint rows, disjunct node) pair per DNF disjunct of p,
   *   i.e. one per cone
   */
  const std::vector<std::pair<std::vector<std::string>, Node>>
  convertQFLIAToMatrices(Node n);

  /**
   * Eager path: build a Normaliz cone for every DNF disjunct of the predicate
   * and accumulate the star constraints over all of them. Empty (infeasible)
   * cones are skipped.
   *
   * @param n the STAR_CONTAINS literal; its children after the lambda are the
   *   vector v
   * @param pairs one (constraint rows, disjunct node) pair per disjunct, as
   *   returned by `convertQFLIAToMatrices`
   * @return the non-empty cones, each paired with the disjunct it came from
   *   (used by `getMembershipDisjuncts` for the debug trace), and the star
   *   constraints: fresh multiplier skolems with their side constraints plus
   *   the sum constraints tying v to the cones' contributions. Their
   *   conjunction is equivalent to `v in S*`.
   */
  std::pair<std::vector<std::pair<Node, libnormaliz::Cone<Integer>>>,
            std::vector<Node>>
  getCones(Node n,
           const std::vector<std::pair<std::vector<std::string>, Node>>& pairs);

  /**
   * Lazy path: build the cone for a single disjunct and append it to the list
   * of cones for `n[0]` (the lambda) stored in `d_lazyCones`. If the cone is
   * empty (the disjunct is infeasible) it is not added.
   *
   * @param n the STAR_CONTAINS literal
   * @param pair the disjunct's constraint rows and node, as returned by
   *   `LiaStarUtils::getMatrix`
   */
  void addCone(Node n, const std::pair<std::vector<std::string>, Node>& pair);

  /**
   * Lazy path: return the star constraints over all cones accumulated so far
   * in `d_lazyCones[n[0]]` (the cones added by previous calls to `addCone`).
   *
   * The per-cone constraints (and their fresh skolems) are computed only for
   * cones that have not been processed in a previous call and are accumulated
   * in `d_starConstraints[n[0]]`, so the skolems stay stable across refinement
   * rounds; the sum constraints, which span all cones, are rebuilt from the
   * accumulated `d_lambdas[n[0]]` on each call.
   */
  std::vector<Node> getStarConstraints(Node n);

  /**
   * Debug helper, used only for the "liastar-ext-smt" trace. Builds the
   * *membership* encoding `v in S`: one existentially quantified formula per
   * (cone, module generator) stating that v is the single element
   * `g + sum_j l_j h_j` of that cone. The disjunction of all returned
   * formulas is equivalent to the predicate itself, which the emitted trace
   * queries let an external solver verify.
   *
   * @param n the STAR_CONTAINS literal
   * @param cones the cones with their originating disjuncts, as returned by
   *   `getCones`
   * @return each membership formula paired with the disjunct it encodes
   */
  std::vector<std::pair<Node, Node>> getMembershipDisjuncts(
      Node n, std::vector<std::pair<Node, libnormaliz::Cone<Integer>>>& cones);

  /**
   * Performs the eager Hilbert-basis reduction for a single STAR_CONTAINS
   * literal. Generates the star reduction lemma equating `literal` with the
   * conjunction of star constraints derived from the cones of `lambda`
   * (== literal[0]), and sends it via the inference manager. Does nothing if
   * the literal has already been processed.
   */
  void eagerCheckStar(Node literal, Node lambda);

  /**
   * Performs one round of the lazy Hilbert-basis reduction for a single
   * STAR_CONTAINS literal: refines the literal's subsolver with the negations
   * of the cone-disjuncts discovered since the previous round, then delegates
   * to `lazyHilbert`. Does nothing if the literal has been fully reduced.
   */
  void lazyCheckStar(Node literal, Node lambda);

  /**
   * A persistent, incremental subsolver dedicated to one lambda (one
   * STAR_CONTAINS predicate). It is used to enumerate the convex cells of the
   * predicate's satisfying region: it is seeded once with the (nonnegative)
   * predicate at the base user level and then refined across rounds with the
   * negations of the discovered cone-disjuncts, either one assertion per
   * disjunct (the default) or as a single cumulative refined formula under
   * push/pop (option arith-liastar-push-pop); see `lazyCheckStar`.
   */
  struct Subsolver
  {
    /** the incremental QF_LIA subsolver. */
    std::unique_ptr<SolverEngine> engine;
    /** the lambda's bound variables ... */
    std::vector<Node> from;
    /** ... and the fresh skolem constants substituted for them, since a
     * subsolver cannot be given a formula with free (bound) variables. */
    std::vector<Node> to;
    /**
     * The (nonnegative) predicate in skolem space. It is already asserted in
     * `engine` at the base user level (so it survives every pop); it is kept
     * only to read off the predicate's atoms when building a disjunct from
     * the model.
     */
    Node base;
    /**
     * Push/pop strategy only: the union (disjunction), in skolem space, of
     * the cone-disjuncts discovered so far. Its negation is the refined
     * formula currently asserted in `engine`.
     */
    Node covered;
    /** Push/pop strategy only: whether a refined formula is currently
     * asserted, i.e. whether `engine` has a pushed frame to pop before
     * asserting the next refined formula. */
    bool pushed = false;
    /** number of cones in `d_lazyCones[lambda]` already negated in `engine`
     * (or, for the push/pop strategy, folded into `covered`). */
    size_t negated = 0;
  };

  /**
   * Returns the subsolver for `lambda`, creating and seeding it (with the
   * nonnegative predicate) on first use.
   */
  Subsolver& getSubsolver(Node lambda);

  /**
   * One lazy refinement round for `literal`: ask the subsolver for a model in
   * a region of the predicate not yet covered by a cone, read off the convex
   * cell containing it (`LiaStarUtils::getDisjunct`), and hand it to
   * `processDisjunct`.
   */
  void lazyHilbert(Node literal, Subsolver& sub);

  /**
   * Shared tail of one lazy refinement round (used by both the subsolver and
   * the main-solver enumeration): turn `disjunct` -- a freshly discovered
   * cell of the predicate, in bound-variable space -- into a cone, rebuild
   * the star constraints over all cones found so far, and emit the reduction
   * lemma: guarded by a fresh boolean while the star is still an
   * under-approximation (`complete` false), unconditional once every cell is
   * covered (`complete` true, `disjunct` is then the false constraint).
   */
  void processDisjunct(Node literal, Node disjunct, bool complete);

  /**
   * State for enumerating the convex cells of one lambda's predicate in the
   * main solver (option arith-liastar-main-solver), replacing the dedicated
   * subsolver. The lambda's bound variables are replaced by fresh skolems
   * (`from` -> `to`) that live in the main solver, constrained through a
   * chain of stage guards: h_0 => base, and for every discovered
   * cone-disjunct D_k a fresh h_k with h_k => h_{k-1} and h_k => not(D_k)
   * (two constant-size lemmas per stage, accumulate style). The current
   * stage guard h_k therefore activates `base and not(D_1) ... and not(D_k)`,
   * i.e. it places the skolems in a cell not yet covered by a cone; the cell
   * is then read off the main solver's candidate arithmetic model.
   *
   * The enumeration is driven by the literal itself: each stage emits the
   * (satisfiability-preserving) driver lemma
   *     literal => (p[v] or star_k or h_k),
   * so a model that claims the literal without certifying it must activate
   * h_k and thereby exhibit a fresh cell; once every cell is covered the h_k
   * branch closes by conflict and the driver leaves exactly the certified
   * branches. Completeness is additionally detected when the SAT solver
   * fixes the stage guard false at level 0 (`Valuation::isFixed`), at which
   * point the exact reduction is emitted.
   */
  struct MainEnum
  {
    /** the lambda's bound variables ... */
    std::vector<Node> from;
    /** ... and the fresh skolems substituted for them in the main solver. */
    std::vector<Node> to;
    /** The (nonnegative) predicate in skolem space. It is asserted under the
     * first stage guard; it is also used to read off the predicate's atoms
     * when building a disjunct from the model. */
    Node base;
    /** The current stage guard h_k (a decision variable, biased true). */
    Node guard;
    /** number of cones in `d_lazyCones[lambda]` already negated via stage
     * guards. */
    size_t negated = 0;
  };

  /**
   * Returns the main-solver enumeration state for `lambda`, creating it (and
   * queueing its seed lemmas: the guard split and `guard => base`) on first
   * use.
   */
  MainEnum& getMainEnum(Node lambda);

  /**
   * One refinement round of the main-solver lazy strategy for `literal`:
   * depending on the guard's value in the current SAT assignment, read a
   * fresh cell from the candidate model (guard true), conclude completeness
   * (guard fixed false), or bias the guard and wait (otherwise). See
   * `MainEnum`.
   */
  void mainSolverCheckStar(Node literal,
                           Node lambda,
                           const std::map<Node, Node>& arithModel);

  /**
   * Read the cell of `en.base` containing the current candidate arithmetic
   * model: fix the truth value of every atom of `en.base` under `arithModel`
   * (consulting `TheoryArith::getCandidateModelValue` for skolems missing
   * from the map) and return the conjunction in bound-variable space.
   * Returns the null node if some atom cannot be evaluated to a constant.
   */
  Node getModelDisjunct(MainEnum& en, const std::map<Node, Node>& arithModel);

  /**
   * Queue a main-solver enumeration lemma (InferenceId ARITH_LIA_STAR_ENUM),
   * skipping lemmas that rewrite to a constant.
   */
  void addEnumLemma(Node lemma);

  /**
   * Open a new enumeration stage for `en`: a fresh guard that activates the
   * previous stage's constraints plus the negation of the newly covered
   * cell `skolemDisjunct` (in skolem space).
   */
  void advanceStage(MainEnum& en, Node skolemDisjunct);

  /**
   * Emit, once per (literal, stage), the driver lemma
   * `literal => (p[v] or star or guard)`; see `MainEnum`.
   */
  void emitDriverLemma(Node literal, MainEnum& en);

  /** node manager */
  NodeManager* d_nm;
  /** commonly used terms */
  Node d_true;
  Node d_false;
  Node d_zero;
  Node d_one;
  /** The theory of arithmetic containing this extension. */
  TheoryArith& d_arith;
  /** A reference to the arithmetic state object. */
  TheoryState& d_astate;
  /** The inference manager of TheoryArith, used to send lemmas. */
  InferenceManager& d_im;
  /**
   * The number of times the main check method (checkFullEffort) has been
   * called. Currently only incremented; intended for interleaving strategies.
   */
  unsigned d_checkCounter;
  /** Callback for the extended theory below. */
  ExtTheoryCallback d_extTheoryCb;
  /** Extended theory, responsible for context-dependent simplification. */
  ExtTheory d_extTheory;
  /** Do we have any liaStar terms? */
  context::CDO<bool> d_hasLiaStarTerms;
  /**
   * The STAR_CONTAINS literals already fully reduced: eagerly reduced
   * literals, and lazily reduced literals whose cone coverage is complete. No
   * further lemmas are generated for these.
   */
  std::vector<Node> d_processedStarTerms;

  /**
   * The cones accumulated so far during the lazy Hilbert-basis reduction,
   * keyed by lambda. Each call to `addCone` appends the cone for the current
   * disjunct, and `getStarConstraints` computes the starLia constraints for
   * the newly added cones, accumulating them across calls.
   */
  std::map<Node, std::vector<std::pair<Node, libnormaliz::Cone<Integer>>>>
      d_lazyCones;

  /**
   * The per-cone starLia constraints computed so far for each lambda node
   * (`n[0]`). `getStarConstraints` only generates the skolems and constraints
   * for cones in `d_lazyCones` that have not been processed yet, appending
   * them here, so previously computed constraints (and their skolems) are
   * reused across refinement rounds. These are the constraints that are
   * independent of the other cones (the (>= mu 0), (>= l 0), and
   * (=> (= mu 0) (= l 0)) constraints); the sum constraints span all cones
   * and are rebuilt each call.
   */
  std::map<Node, std::vector<Node>> d_starConstraints;
  /**
   * The (point, rays) contributions computed so far for each lambda node,
   * kept in step with `d_starConstraints`. They are used to rebuild the sum
   * constraints over all cones on each call to `getStarConstraints`.
   */
  std::map<Node, std::vector<std::pair<Vector, std::vector<Vector>>>> d_lambdas;
  /** The number of cones in `d_lazyCones[n[0]]` already processed. */
  std::map<Node, size_t> d_processedCones;

  /**
   * The last starLia under-approximation (`star`) computed for each
   * STAR_CONTAINS literal by `lazyHilbert`. The model-value check in
   * `checkFullEffort` uses it to skip refinement when the current model
   * already satisfies the predicate or this under-approximation.
   */
  std::map<Node, Node> d_lastStarLia;

  /**
   * The fresh boolean guard of the last (still active) tentative reduction
   * `g => (literal = star)` emitted for each STAR_CONTAINS literal by
   * `lazyHilbert`. When a later round produces a larger under-approximation,
   * the previous guard is deactivated (we assert `(not g)`), so at most one
   * tentative reduction is active per literal.
   */
  std::map<Node, Node> d_lastGuard;

  /**
   * Lazy proof generator for the lia* lemmas (split, non-negativity, and
   * STAR_CONTAINS reduction). Allocated only when proofs are enabled.
   */
  std::unique_ptr<LiaStarProofGenerator> d_proofGen;

  /**
   * The incremental subsolver for each lambda (STAR_CONTAINS predicate). Each
   * is created lazily and persists for the lifetime of the extension, so the
   * predicate's cells are enumerated incrementally across refinement rounds.
   */
  std::map<Node, Subsolver> d_subsolvers;

  /**
   * The main-solver enumeration state for each lambda (option
   * arith-liastar-main-solver). Created lazily, like `d_subsolvers`.
   */
  std::map<Node, MainEnum> d_mainEnums;

  /**
   * The stage guard for which the driver lemma
   * `literal => (p[v] or star or guard)` was last emitted, per literal. Used
   * to emit the driver exactly once per (literal, stage).
   */
  std::map<Node, Node> d_lastDriver;
}; /* class LiaStarExtension */

}  // namespace liastar
}  // namespace arith
}  // namespace theory
}  // namespace cvc5::internal

#endif /* CVC5__THEORY__ARITH__LIASTAR_EXTENSION_H */

#endif /* CVC5_USE_NORMALIZ */
