/******************************************************************************
 * Top contributors (to current version):
 *   Mudathir Mohamed
 *
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Extension to the theory of arithmetic handling lia star operator.
 */

#ifdef CVC5_USE_NORMALIZ

#ifndef CVC5__THEORY__ARITH__LIASTAR_EXTENSION_H
#define CVC5__THEORY__ARITH__LIASTAR_EXTENSION_H

#include <map>
#include <vector>

#include "expr/node.h"
#include "libnormaliz/libnormaliz.h"
#include "proof/proof_set.h"
#include "smt/env_obj.h"
#include "theory/arith/liastar/liastar_proof_generator.h"
#include "theory/ext_theory.h"
#include "theory/theory.h"
#include "util/result.h"

namespace cvc5::internal {
namespace theory {
namespace arith {

class InferenceManager;
class TheoryArith;

namespace liastar {

class CDProof;

// Arbitrary‑precision integers.
typedef mpz_class Integer;
// type the constraint matrix
typedef std::vector<std::vector<Integer>> Matrix;
typedef std::vector<Node> Vector;
/** Liastar extension class
 *
 * This class implements model-based refinement schemes
 * for liastar formulas.
 *
 * - Levatich, M., Bjorner, N., Piskac, R., Shoham, S. (2020).
 *   Solving LIA* Using Approximations.
 *   VMCAI 2020.
 *   https://doi.org/10.1007/978-3-030-39322-9_17
 *
 * It's main functionality is a check(...) method,
 * which is called by TheoryArithPrivate either:
 * (1) at full effort with no conflicts or lemmas emitted, or
 * (2) at last call effort.
 * In this method, this class calls d_im.lemma(...)
 * for valid arithmetic theory lemmas, based on the current set of assertions,
 * where d_im is the inference manager of TheoryArith.
 */
class LiaStarExtension : EnvObj
{
  typedef context::CDHashSet<Node> NodeSet;

 public:
  LiaStarExtension(Env& env, TheoryArith& containing);
  ~LiaStarExtension();
  /**
   * Does non-context dependent setup for a node connected to a theory.
   */
  void preRegisterTerm(TNode n);

  /**
   * Performs the main checks for liastar arithmetic, based on the current
   * (linear) arithmetic model from `arithModel`. This method may already send
   * lemmas, but most lemmas are buffered and sent at LAST_CALL effort by
   * TheoryArith. The motivation for this strategy is to allow other
   * non-terminating theories (e.g. quantifiers, strings) to run full effort
   * checks, before sending the lemmas generated by liastar.
   *
   * The argument arithModel is a map of the form { v1 -> c1, ..., vn -> cn }
   * which represents the linear arithmetic theory solver's contribution to the
   * current candidate model where v1, ..., vn are arithmetic variables and
   * c1, ..., cn are constants.
   */
  void checkFullEffort(std::map<Node, Node>& arithModel,
                       const std::set<Node>& termSet);

  /** Does this class need a call to check(...) at last call effort? */
  bool hasLiaStarTerms() const { return d_hasLiaStarTerms; }

 private:
  /** get assertions
   *
   * Let M be the set of assertions known by THEORY_ARITH. This function adds a
   * set of literals M' to assertions such that M' and M are equivalent.
   *
   * Examples of how M' differs with M:
   * (1) M' may not include t < c (in M) if t < c' is in M' for c' < c, where
   * c and c' are constants,
   * (2) M' may contain t = c if both t >= c and t <= c are in M.
   */
  void getAssertions(std::vector<Node>& assertions);

  Node isNotZeroVector(Node v);

  /**
   * Argument n must be a node of the form (int.star-contains ((x1 Int) ... (xn
   * Int)) p v) This functions convert the predicate p (which in QFLIA) to a
   * list of matrices representing a disjunction of set of inequalities in
   * Normaliz matrix form A x b >= 0 where A is a matrix and x = (x1 ... xn 1).
   * This form is used
   */
  const std::vector<std::pair<std::vector<std::string>, Node>>
  convertQFLIAToMatrices(Node n);

  std::pair<std::vector<std::pair<Node, libnormaliz::Cone<Integer>>>,
            std::vector<Node>>
  getCones(Node n,
           const std::vector<std::pair<std::vector<std::string>, Node>>& pairs);

  /**
   * Similar to `getCones`, but processes a single constraint pair instead of a
   * list. The cone derived from `pair` is appended to the list of cones for
   * `n[0]` (the lambda) stored in `d_lazyCones`. If the cone derived from
   * `pair` is empty it is not added.
   */
  void addCone(Node n, const std::pair<std::vector<std::string>, Node>& pair);

  /**
   * Returns the starLia constraints over all cones accumulated so far in
   * `d_lazyCones[n[0]]` (the cones added by previous calls to `addCone`).
   *
   * The per-cone constraints (and their skolems) are computed only for cones
   * that have not been processed in a previous call, and are accumulated in
   * `d_starConstraints[n[0]]`; the sum constraints, which span all cones, are
   * rebuilt from the accumulated `d_lambdas[n[0]]` on each call.
   */
  std::vector<Node> getStarConstraints(Node n);

  std::vector<std::pair<Node, Node>> getLia(
      Node n, std::vector<std::pair<Node, libnormaliz::Cone<Integer>>>& cones);

  /**
   * Performs the eager Hilbert-basis reduction for a single STAR_CONTAINS
   * literal. Generates the star reduction lemma equating `literal` with the
   * conjunction of star constraints derived from the cones of `lambda`
   * (== literal[0]), and sends it via the inference manager. Does nothing if
   * the literal has already been processed.
   */
  void eagerCheckStar(Node literal, Node lambda);
  void lazyCheckStar(Node literal, Node lambda);
  void lazyHilbert(Node literal, Node formula);

  /** node manager */
  NodeManager* d_nm;
  /** commonly used terms */
  Node d_true;
  Node d_false;
  Node d_zero;
  Node d_one;
  // The theory of arithmetic containing this extension.
  TheoryArith& d_arith;
  /** A reference to the arithmetic state object */
  TheoryState& d_astate;
  InferenceManager& d_im;
  /**
   * The number of times we have the called main check method
   * (modelBasedRefinement). This counter is used for interleaving strategies.
   */
  unsigned d_checkCounter;
  ExtTheoryCallback d_extTheoryCb;
  /** Extended theory, responsible for context-dependent simplification. */
  ExtTheory d_extTheory;
  /** Do we have any liaStar terms? */
  context::CDO<bool> d_hasLiaStarTerms;
  std::vector<Node> d_processedStarTerms;
  // std::map<Node, std::vector<std::pair<Node, Node>> d_lazyStarTerms;

  /**
   * The cones accumulated so far during the lazy Hilbert-basis reduction. Each
   * call to `addCone` appends the cone for the current disjunct here, and
   * `getStarConstraints` computes the starLia constraints for the newly added
   * cones, accumulating them across calls.
   */
  std::map<Node, std::vector<std::pair<Node, libnormaliz::Cone<Integer>>>>
      d_lazyCones;

  /**
   * The per-cone starLia constraints computed so far for each lambda node
   * (`n[0]`). `getStarConstraints` only generates the skolems and constraints
   * for cones in `d_lazyCones` that have not been processed yet, appending them
   * here, so previously computed constraints (and their skolems) are reused
   * across refinement rounds. These are the constraints that are independent of
   * the other cones (the (>= mu 0), (>= l 0), and (=> (= mu 0) (= l 0))
   * constraints); the sum constraints span all cones and are rebuilt each call.
   */
  std::map<Node, std::vector<Node>> d_starConstraints;
  /**
   * The lambdas (point and rays) computed so far for each lambda node, kept in
   * step with `d_starConstraints`. They are used to rebuild the sum
   * constraints over all cones on each call to `getStarConstraints`.
   */
  std::map<Node, std::vector<std::pair<Vector, std::vector<Vector>>>>
      d_lambdas;
  /** The number of cones in `d_lazyCones[n[0]]` already processed. */
  std::map<Node, size_t> d_processedCones;

  /**
   * A CDProofSet that hands out CDProof objects for lemmas.
   */
  std::unique_ptr<CDProofSet<CDProof>> d_proof;

  /**
   * Lazy proof generator for the lia* lemmas (split, non-negativity, and
   * STAR_CONTAINS reduction). Allocated only when proofs are enabled.
   */
  std::unique_ptr<LiaStarProofGenerator> d_proofGen;

}; /* class LiaStarExtension */

}  // namespace liastar
}  // namespace arith
}  // namespace theory
}  // namespace cvc5::internal

#endif /* CVC5__THEORY__ARITH__LIASTAR_EXTENSION_H */

#endif /* CVC5_USE_NORMALIZ */